%
% Parameters to make motor imagery data resembling one in BCI Competition IV (Tangermann & al. 2012)
%

% These events mark starts of trials that are to be classified
classEvents = {'left','right'};

% Parameters controlling experiment timeline generation:  when events happen
timelineParams = { 'samplingFreq', 200, 'eventList', { ...
	  	{'when', {@when_trials, 'events',classEvents, ...
		    'numTrials',10, ... 
			'trialLengthMs',4000, 'restLengthMs', 2000, ...
			'trialOrder', 'random', 'includeRest', true}}, ...	
		{'when', {@when_random, 'events',{'eyeblink'},'eventFreq',0.1}}, ...
		{'when', {@when_random, 'events',{'eyemove'},'eventFreq',0.2,'randomMaxDurationMs',2000}}, ...		
		{'when', {@when_always, 'events',{'noise'}}} ...
	} ...
};
			
% List reactions to the events on the timeline
effectParams = { ...	
	  {'SNR', 1.0, 'name', 'signalLeft', 'triggeredBy', 'left', ...
		'what',  {@gen_desync, 'centerHz',12,'widthHz',1,'reduction',0.5}, ...
		'where', {@where_heuristic, 'position','rightMC'} }, ...	
	  {'SNR', 1.0, 'name', 'signalRight', 'triggeredBy', 'right', ...
		'what',  {@gen_desync, 'centerHz',12,'widthHz',1,'reduction',0.5}, ...
		'where', {@where_heuristic, 'position','leftMC'}}, ...		
	  {'SNR', 0.1, 'name', 'blinks', 'triggeredBy', 'eyeblink', ...
		'what',  @noise_eyeblinks, ...
		'where', {@where_heuristic, 'position','eyes'}}, ...
	  {'SNR', 0.1, 'name', 'eyemove', 'triggeredBy', 'eyemove', ...
		'what',  @noise_eyemovement, ...
		'where', {@where_heuristic, 'position','eyes'}}, ...		
	  {'SNR', 0.005, 'name', 'noise', 'triggeredBy', 'noise', ...
		'what',  {@noise_spectrally_colored, 'subType','fake', 'strength', [1.0 0.5, 0.3]}, ...
		'where', {@where_whole_surface}} ...		 % example of a convenience function that doesn't need params
};

