%
% Classic pipeline using LDA on CSP/Bandpower features, used e.g. with motor imagery
%

if(~exist('allPipelines','var'))
	allPipelines={};
end

allPipelines = { allPipelines{:}, ...
	{'name','csp-bandpower-lda', 'classEvents', classEvents, 'processors', { ...
	  {@proc_csp_bandpower, 'logFeats',false,'freqLow',8,'freqHigh',30, ...
			   'dim', 2, 'tikhonov', 0.5, 'shrink', 0.5}, ...
	  @proc_normalize, ...
	  {@proc_lda} } } ...
};

